.SILENT:

VMFILES = clusteringtool.tcl pkgIndex.tcl
VMVERSION = 0.1
DIR = $(PLUGINDIR)/noarch/tcl/clusteringtool$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying clusteringtool $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

